language: c

os: linux

maxtrix:
  include:
    - dist: focal
      env:
        - cc=gcc
    - dist: focal
      env:
        - cc=clang

install:
  - sudo apt-get install libglew-dev mesa-common-dev build-essential libglm-dev mesa-utils libgl1-mesa-dev libgl1-mesa-glx libx11-dev libpng-dev valgrind

before_script:
  - export CC=${cc}

script:
  - make clean all && chmod 700 sh/memcheck.sh && ./sh/memcheck.sh
