os: linux

dist: focal

language: c

install:
  - sudo apt-get install binutils cmake libglew-dev mesa-common-dev build-essential libglm-dev mesa-utils libgl1-mesa-dev libgl1-mesa-glx libx11-dev libpng-dev

compiler:
  - clang
  - gcc

script:
  - ./sh/configure.sh && make clean all
