const vk = @import ("vulkan");

const log     = @import ("../log.zig").Log;
const Profile = log.Profile;

pub const BaseDispatch = vk.BaseWrapper (
.{
  .createInstance                       = true,
  .enumerateInstanceLayerProperties     = log.level > @intFromEnum (Profile.TURBO),
  .enumerateInstanceExtensionProperties = log.level > @intFromEnum (Profile.TURBO),
  .getInstanceProcAddr                  = true,
});

pub const InstanceDispatch = vk.InstanceWrapper (
.{
  .destroyInstance                         = true,
  .createDebugUtilsMessengerEXT            = log.level > @intFromEnum (Profile.TURBO),
  .destroyDebugUtilsMessengerEXT           = log.level > @intFromEnum (Profile.TURBO),
  .destroySurfaceKHR                       = true,
  .getPhysicalDeviceSurfaceSupportKHR      = true,
  .getPhysicalDeviceSurfaceCapabilitiesKHR = true,
  .getPhysicalDeviceSurfaceFormatsKHR      = true,
  .getPhysicalDeviceSurfacePresentModesKHR = true,
  .enumeratePhysicalDevices                = true,
  .getPhysicalDeviceProperties             = true,
  .getPhysicalDeviceFeatures               = true,
  .getPhysicalDeviceFormatProperties       = true,
  .getPhysicalDeviceQueueFamilyProperties  = true,
  .createDevice                            = true,
  .getDeviceProcAddr                       = true,
  .enumerateDeviceExtensionProperties      = true,
  .getPhysicalDeviceMemoryProperties       = true,
});

pub const DeviceDispatch = vk.DeviceWrapper (
.{
  .destroyDevice               = true,
  .getDeviceQueue              = true,
  .createSwapchainKHR          = true,
  .destroySwapchainKHR         = true,
  .getSwapchainImagesKHR       = true,
  .createImageView             = true,
  .destroyImageView            = true,
  .createShaderModule          = true,
  .destroyShaderModule         = true,
  .createPipelineLayout        = true,
  .destroyPipelineLayout       = true,
  .createRenderPass            = true,
  .destroyRenderPass           = true,
  .createGraphicsPipelines     = true,
  .destroyPipeline             = true,
  .createFramebuffer           = true,
  .destroyFramebuffer          = true,
  .createCommandPool           = true,
  .destroyCommandPool          = true,
  .resetCommandPool            = true,
  .allocateCommandBuffers      = true,
  .freeCommandBuffers          = true,
  .beginCommandBuffer          = true,
  .cmdBeginRenderPass          = true,
  .cmdBindPipeline             = true,
  .cmdSetViewport              = true,
  .cmdSetScissor               = true,
  .cmdEndRenderPass            = true,
  .endCommandBuffer            = true,
  .createSemaphore             = true,
  .destroySemaphore            = true,
  .createFence                 = true,
  .destroyFence                = true,
  .waitForFences               = true,
  .resetFences                 = true,
  .acquireNextImageKHR         = true,
  .resetCommandBuffer          = true,
  .queueSubmit                 = true,
  .queuePresentKHR             = true,
  .deviceWaitIdle              = true,
  .createBuffer                = true,
  .destroyBuffer               = true,
  .getBufferMemoryRequirements = true,
  .allocateMemory              = true,
  .freeMemory                  = true,
  .bindBufferMemory            = true,
  .mapMemory                   = true,
  .unmapMemory                 = true,
  .cmdBindVertexBuffers        = true,
  .cmdCopyBuffer               = true,
  .queueWaitIdle               = true,
  .cmdBindIndexBuffer          = true,
  .cmdDrawIndexed              = true,
  .createDescriptorSetLayout   = true,
  .destroyDescriptorSetLayout  = true,
  .createDescriptorPool        = true,
  .destroyDescriptorPool       = true,
  .allocateDescriptorSets      = true,
  .updateDescriptorSets        = true,
  .cmdBindDescriptorSets       = true,
  .createImage                 = true,
  .destroyImage                = true,
  .getImageMemoryRequirements  = true,
  .bindImageMemory             = true,
  .createSampler               = true,
  .destroySampler              = true,
  .getImageSubresourceLayout   = true,
  .cmdPipelineBarrier          = true,
  .cmdBlitImage                = true,
  .cmdCopyImage                = true,
});
