#!/bin/sh

main ()
{
  done_def='DONE - commit linked to an opened task and close it'
  progress_def='PROGRESS - commit linked to an opened task and do not close it'
  fix_def='FIX - commit linked to a closed task'
  one_task_headers='done\|progress\|fix'

  one_task_syntax='[<DONE|PROGRESS|FIX> #<task ID>] <body>'
  one_task_commit='\[\('"${one_task_headers}"'\) #[0-9]\+\] .\+'

  update_def='UPDATE - commit not linked to an opened task'
  revert_def='REVERT - cancel problematic commit(s) (with ID(s) in <body>)'
  no_task_headers='update\|revert'

  no_task_syntax='[<UPDATE|REVERT>] <body>'
  no_task_commit='\[\('"${no_task_headers}"'\)\] .\+'

  release_def='RELEASE - commit related to a major/minor release'
  patch_def='PATCH - commit related to a patch'
  milestone_headers='release\|patch'

  milestone_syntax='[<RELEASE|PATCH>] <body>'
  milestone_commit='\[\('"${milestone_headers}"'\)\] .\+'

  merge_def='MERGE - solve conflicts'
  init_def='INIT - first commit'
  typo_def='TYPO - commit with insignificant content'
  specific_headers='merge\|init\|typo'

  specific_syntax='[<MERGE|INIT|TYPO>]'
  specific_commit='\[\('"${specific_headers}"'\)\]'

  first_line='Commit message allows only one of these syntaxes:'

  replace_me='@@@'

  error="${first_line}
${replace_me}
${one_task_syntax}

  ${done_def}
  ${progress_def}
  ${fix_def}
${replace_me}
${no_task_syntax}

  ${update_def}
  ${revert_def}
${replace_me}
${milestone_syntax}

  ${release_def}
  ${patch_def}
${replace_me}
${specific_syntax}

  ${merge_def}
  ${init_def}
  ${typo_def}
"

  reset='\033[m'
  bold='\033[1m'
  red='\033[38;5;11m'
  orange='\033[38;5;214m'
  yellow='\033[38;5;9m'
  apple='\033[38;5;10m'
  green='\033[38;5;42m'
  cyan='\033[38;5;51m'
  blue='\033[38;5;69m'
  navy='\033[38;5;21m'
  purple='\033[38;5;129m'
  pink='\033[38;5;201m'

  done_color="${apple}"
  progress_color="${yellow}"
  fix_color="${red}"
  update_color="${orange}"
  revert_color="${pink}"
  release_color="${navy}"
  patch_color="${purple}"
  merge_color="${green}"
  init_color="${cyan}"
  typo_color="${blue}"

  dashes="$(printf %"$(printf '%s' "${error}" | awk "{ print length }" | sort -n | tail -n1)"s | tr ' ' '-')"

  match="${one_task_commit}"'\|'"${no_task_commit}"'\|'"${milestone_commit}"'\|'"${specific_commit}"

  if ! grep -q "${match}" "${1}"
  then
    printf '%s' "${error}" | sed 's/^'"${replace_me}"'$/'"${dashes}"'/;'"$(printf "s/DONE/${bold}${done_color}done${reset}/;s/PROGRESS/${bold}${progress_color}progress${reset}/;s/FIX/${bold}${fix_color}fix${reset}/;s/UPDATE/${bold}${update_color}update${reset}/;s/REVERT/${bold}${revert_color}revert${reset}/;s/RELEASE/${bold}${release_color}release${reset}/;s/PATCH/${bold}${patch_color}patch${reset}/;s/MERGE/${bold}${merge_color}merge${reset}/;s/INIT/${bold}${init_color}init${reset}/;s/TYPO/${bold}${typo_color}typo${reset}/")" 1>&2
    return 1
  fi
}

main "${@}"
