#ifndef SPACEPORN_UTIL_H
#define SPACEPORN_UTIL_H

#include "config.h"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <systemd/sd-journal.h>
#include <GL/glew.h>
#include <GL/glx.h>

#if HAVE_OPENMP
#include <omp.h>
#endif

#include "GLFW/glfw3.h"

#define DEBUG GCC_DEBUG

enum RoadmapID
{
  IMPROVELOGSHADER_REGCOMP_FAILED_RM = -26,
  IMPROVELOGSHADER_REGEXEC_FAILED_RM = -25,
  IMPROVELOGSHADER_REPLACE_REGEXEC_FAILED_RM = -24,
  IMPROVELOGSHADER_REPLACE_REALLOC_FAILED_RM = -23,
  IMPROVELOGSHADER_REPLACE_REGCOMP_FAILED_RM = -22,
  SARH_REGEXEC_FAILED_RM = -21,
  SARH_REPLACE_2_REGEXEC_FAILED_RM = -20,
  SARH_REPLACE_2_REALLOC_FAILED_RM = -19,
  SARH_REPLACE_2_REGCOMP_FAILED_RM = -18,
  SARH_ADDMARKERS_IN_LOOP_REALLOC_FAILED_RM = -17,
  SARH_READFILE_FOPEN_FAILED_RM = -16,
  SARH_READFILE_BUFFER_MALLOC_FAILED_RM = -15,
  SARH_HEADER_REALLOC_FAILED_RM = -14,
  SARH_HEADERS_REALLOC_FAILED_RM = -13,
  SARH_REPLACE_1_REGEXEC_FAILED_RM = -12,
  SARH_REPLACE_1_REALLOC_FAILED_RM = -11,
  SARH_REPLACE_1_REGCOMP_FAILED_RM = -10,
  REPLACE_REGEXEC_FAILED_RM = -9,
  REPLACE_REALLOC_FAILED_RM = -8,
  REPLACE_REGCOMP_FAILED_RM = -7,
  SARH_ADDMARKERS_REALLOC_FAILED_RM = -6,
  SARH_HEADER_MALLOC_FAILED_RM = -5,
  SARH_HEADERS_MALLOC_FAILED_RM = -4,
  SARH_REGCOMP_FAILED_RM = -3,
  FOPEN_FAILED_RM = -2,
  BUFFER_MALLOC_FAILED_RM = -1,
// -------------------------------------------------------------------   0
  EXIT_SUCCESS_RM = 0,
  SLIDEMODE_SUCCESS_RM,
  BREAK_SUCCESS_RM,
  PATH_MALLOC_FAILED_RM,
  FSHADERPATH_MALLOC_FAILED_RM,
// -------------------------------------------------------------------   5
  VSHADERDIR_MALLOC_FAILED_RM,
  VSHADERPATH_MALLOC_FAILED_RM,
  GLFWINIT_FAILED_RM,
  GLFWCREATEWINDOW_FAILED_RM,
  GLEWINIT_FAILED_RM,
// -------------------------------------------------------------------  10
  FOPEN_VERTEX_FILE_FAILED_RM,
  BUFFER_VERTEX_FILE_MALLOC_FAILED_RM,
  FOPEN_FRAGMENT_FILE_FAILED_RM,
  BUFFER_FRAGMENT_FILE_MALLOC_FAILED_RM,
  VERTEX_SHADER_COMPILATION_FAILED_RM,
// -------------------------------------------------------------------  15
  FRAGMENT_SHADER_COMPILATION_FAILED_RM,
  LINKING_PROGRAM_FAILED_RM,
  OPENGL_ERROR_RM,
  VERTEX_FILE_SARH_REGCOMP_FAILED_RM,
  VERTEX_FILE_SARH_HEADERS_MALLOC_FAILED_RM,
// -------------------------------------------------------------------  20
  FRAGMENT_FILE_SARH_REGCOMP_FAILED_RM,
  FRAGMENT_FILE_SARH_HEADERS_MALLOC_FAILED_RM,
  VERTEX_FILE_SARH_HEADER_MALLOC_FAILED_RM,
  VERTEX_FILE_SARH_ADDMARKERS_REALLOC_FAILED_RM,
  VERTEX_FILE_SARH_REPLACE_1_REGCOMP_FAILED_RM,
// -------------------------------------------------------------------  25
  VERTEX_FILE_SARH_REPLACE_1_REALLOC_FAILED_RM,
  VERTEX_FILE_SARH_REPLACE_1_REGEXEC_FAILED_RM,
  VERTEX_FILE_SARH_HEADERS_REALLOC_FAILED_RM,
  VERTEX_FILE_SARH_HEADER_REALLOC_FAILED_RM,
  VERTEX_FILE_SARH_READFILE_BUFFER_MALLOC_FAILED_RM,
// -------------------------------------------------------------------  30
  VERTEX_FILE_SARH_READFILE_FOPEN_FAILED_RM,
  VERTEX_FILE_SARH_ADDMARKERS_IN_LOOP_REALLOC_FAILED_RM,
  VERTEX_FILE_SARH_REPLACE_2_REGCOMP_FAILED_RM,
  VERTEX_FILE_SARH_REPLACE_2_REALLOC_FAILED_RM,
  VERTEX_FILE_SARH_REPLACE_2_REGEXEC_FAILED_RM,
// -------------------------------------------------------------------  35
  FRAGMENT_FILE_SARH_HEADER_MALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_ADDMARKERS_REALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_REPLACE_1_REGCOMP_FAILED_RM,
  FRAGMENT_FILE_SARH_REPLACE_1_REALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_REPLACE_1_REGEXEC_FAILED_RM,
// -------------------------------------------------------------------  40
  FRAGMENT_FILE_SARH_HEADERS_REALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_HEADER_REALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_READFILE_BUFFER_MALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_READFILE_FOPEN_FAILED_RM,
  FRAGMENT_FILE_SARH_ADDMARKERS_IN_LOOP_REALLOC_FAILED_RM,
// -------------------------------------------------------------------  45
  FRAGMENT_FILE_SARH_REPLACE_2_REGCOMP_FAILED_RM,
  FRAGMENT_FILE_SARH_REPLACE_2_REALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_REPLACE_2_REGEXEC_FAILED_RM,
  VERTEX_FILE_SARH_REGEXEC_FAILED_RM,
  VERTEX_FILE_ILS_REPLACE_REGCOMP_FAILED_RM,
// -------------------------------------------------------------------  50
  VERTEX_FILE_ILS_REPLACE_REALLOC_FAILED_RM,
  VERTEX_FILE_ILS_REPLACE_REGEXEC_FAILED_RM,
  VERTEX_FILE_ILS_REGCOMP_FAILED_RM,
  VERTEX_FILE_ILS_REGEXEC_FAILED_RM,
  FRAGMENT_FILE_SARH_REGEXEC_FAILED_RM,
// -------------------------------------------------------------------  55
  FRAGMENT_FILE_ILS_REPLACE_REGCOMP_FAILED_RM,
  FRAGMENT_FILE_ILS_REPLACE_REALLOC_FAILED_RM,
  FRAGMENT_FILE_ILS_REPLACE_REGEXEC_FAILED_RM,
  FRAGMENT_FILE_ILS_REGCOMP_FAILED_RM,
  FRAGMENT_FILE_ILS_REGEXEC_FAILED_RM,
// -------------------------------------------------------------------  60
  ATLASTEXTUREPATH_MALLOC_FAILED_RM,
  ATLASTEXELS_MALLOC_FAILED_RM,
  ATLASTEXELROW_MALLOC_FAILED_RM,
  FOPEN_NEW_PNG_FILE_FAILED_RM,
  PNGCREATEWRITESTRUCT_FAILED_RM,
// -------------------------------------------------------------------  65
  PNGCREATEWRITEINFOSTRUCT_FAILED_RM,
  PNG_WRITEJMPBUF_FAILED_RM,
  NO_ATLASPNG_FILENAME_RM,
  FOPEN_ATLASPNG_FILE_FAILED_RM,
  ATLASPNGCREATEREADSTRUCT_FAILED_RM,
// -------------------------------------------------------------------  70
  ATLASPNGCREATEREADINFOSTRUCT_FAILED_RM,
  ATLASPNG_READJMPBUF_FAILED_RM,
  ATLASPNG_DATA_MALLOC_FAILED_RM,
  ATLASPNG_READROWPOINTERS_MALLOC_FAILED_RM,
  BAD_ATLASPNG_DIMENSIONS_RM,
// -------------------------------------------------------------------  75
  PRECOMPUTE_AND_STOP_RM,
  PRECOMPUTE_AND_CONTINUE_RM,
#if DEBUG
  XCREATEDEBUGWINDOW_FAILED_RM,
#endif
  RM_NB
};

#define MSG_LEN 8

typedef struct
{
  enum RoadmapID id;
  char* glsl_file;
} Roadmap;

typedef struct
{
  bool verbose;
  Roadmap roadmap;
} Log;

bool initLog(Log* log);
void writeLog(Log* log, FILE* stream, const char* stdoutstr,
  const char* str, ...);
void freeLog(Log* log);

bool checkOpenGLError(const char* stmt, const char* fname, int line, Log* log);

double timediff(struct timeval* start, struct timeval* end);
int nextpow2(int n);

#define GL_CHECK(stmt, status, log) { \
  stmt; \
  status = checkOpenGLError(#stmt, __FILE__, __LINE__, log); \
  if (!(status)) \
  { \
    break; \
  } \
}

#define MISSINGMAIN_VERTEX_SHADER GCC_MISSINGMAIN_VERTEX
#define ERRONEOUS_VERTEX_SHADER GCC_ERRONEOUS_VERTEX
#define ERRONEOUS_FRAGMENT_SHADER GCC_ERRONEOUS_FRAGMENT

#endif
