#ifndef XTELESKOP_UTIL_H
#define XTELESKOP_UTIL_H

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include <png.h>
#include <GL/glew.h>
#include <GL/glx.h>

#define DEBUG true

enum RoadmapID
{
  IMPROVELOGSHADER_REGCOMP_FAILED_RM = -26,
  IMPROVELOGSHADER_REGEXEC_FAILED_RM = -25,
  IMPROVELOGSHADER_REPLACE_REGEXEC_FAILED_RM = -24,
  IMPROVELOGSHADER_REPLACE_REALLOC_FAILED_RM = -23,
  IMPROVELOGSHADER_REPLACE_REGCOMP_FAILED_RM = -22,
  SARH_REGEXEC_FAILED_RM = -21,
  SARH_REPLACE_2_REGEXEC_FAILED_RM = -20,
  SARH_REPLACE_2_REALLOC_FAILED_RM = -19,
  SARH_REPLACE_2_REGCOMP_FAILED_RM = -18,
  SARH_ADDMARKERS_IN_LOOP_REALLOC_FAILED_RM = -17,
  SARH_READFILE_FOPEN_FAILED_RM = -16,
  SARH_READFILE_BUFFER_MALLOC_FAILED_RM = -15,
  SARH_HEADER_REALLOC_FAILED_RM = -14,
  SARH_HEADERS_REALLOC_FAILED_RM = -13,
  SARH_REPLACE_1_REGEXEC_FAILED_RM = -12,
  SARH_REPLACE_1_REALLOC_FAILED_RM = -11,
  SARH_REPLACE_1_REGCOMP_FAILED_RM = -10,
  REPLACE_REGEXEC_FAILED_RM = -9,
  REPLACE_REALLOC_FAILED_RM = -8,
  REPLACE_REGCOMP_FAILED_RM = -7,
  SARH_ADDMARKERS_REALLOC_FAILED_RM = -6,
  SARH_HEADER_MALLOC_FAILED_RM = -5,
  SARH_HEADERS_MALLOC_FAILED_RM = -4,
  SARH_REGCOMP_FAILED_RM = -3,
  FOPEN_FAILED_RM = -2,
  BUFFER_MALLOC_FAILED_RM = -1,
  EXIT_SUCCESS_RM = 0, // --------------------------------------------   0
  BREAK_SUCCESS_RM,
  GETENV_USERNAME_FAILED_RM,
  FSHADERPATH_MALLOC_FAILED_RM,
  VSHADERPATH_MALLOC_FAILED_RM,
  TEXTUREPATH_MALLOC_FAILED_RM, // -----------------------------------   5
  XOPENDISPLAY_FAILED_RM,
  INVALID_GLX_VERSION_RM,
  GLXCHOOSEFBCONFIG_FAILED_RM,
  XCREATEWINDOW_FAILED_RM,
  GLXCREATECONTEXTATTRIBSARB_UNFOUNDABLE_RM, // ----------------------  10
  SPACE_IN_GLX_EXT_RM,
  UNSUPPORTED_GLX_EXT_RM,
  CONTEXT_CREATION_FAILED_RM,
  GLEWINIT_FAILED_RM,
  FOPEN_VERTEX_FILE_FAILED_RM, // ------------------------------------  15
  BUFFER_VERTEX_FILE_MALLOC_FAILED_RM,
  FOPEN_FRAGMENT_FILE_FAILED_RM,
  BUFFER_FRAGMENT_FILE_MALLOC_FAILED_RM,
  VERTEX_SHADER_COMPILATION_FAILED_RM,
  FRAGMENT_SHADER_COMPILATION_FAILED_RM, // --------------------------  20
  LINKING_PROGRAM_FAILED_RM,
  NO_PNG_FILENAME_RM,
  FOPEN_PNG_FILE_FAILED_RM,
  PNGCREATEREADSTRUCT_FAILED_RM,
  PNGCREATEINFOSTRUCT_FAILED_RM, // ----------------------------------  25
  PNG_JMPBUF_FAILED_RM,
  BAD_PNG_DIMENSIONS_RM,
  PNG_DATA_MALLOC_FAILED_RM,
  PNG_ROWPOINTERS_MALLOC_FAILED_RM,
  OPENGL_ERROR_RM, // ------------------------------------------------  30
  VERTEX_FILE_SARH_REGCOMP_FAILED_RM,
  VERTEX_FILE_SARH_HEADERS_MALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_REGCOMP_FAILED_RM,
  FRAGMENT_FILE_SARH_HEADERS_MALLOC_FAILED_RM,
  VERTEX_FILE_SARH_HEADER_MALLOC_FAILED_RM, // -----------------------  35
  VERTEX_FILE_SARH_ADDMARKERS_REALLOC_FAILED_RM,
  VERTEX_FILE_SARH_REPLACE_1_REGCOMP_FAILED_RM,
  VERTEX_FILE_SARH_REPLACE_1_REALLOC_FAILED_RM,
  VERTEX_FILE_SARH_REPLACE_1_REGEXEC_FAILED_RM,
  VERTEX_FILE_SARH_HEADERS_REALLOC_FAILED_RM, // ---------------------  40
  VERTEX_FILE_SARH_HEADER_REALLOC_FAILED_RM,
  VERTEX_FILE_SARH_READFILE_BUFFER_MALLOC_FAILED_RM,
  VERTEX_FILE_SARH_READFILE_FOPEN_FAILED_RM,
  VERTEX_FILE_SARH_ADDMARKERS_IN_LOOP_REALLOC_FAILED_RM,
  VERTEX_FILE_SARH_REPLACE_2_REGCOMP_FAILED_RM, // -------------------  45
  VERTEX_FILE_SARH_REPLACE_2_REALLOC_FAILED_RM,
  VERTEX_FILE_SARH_REPLACE_2_REGEXEC_FAILED_RM,
  FRAGMENT_FILE_SARH_HEADER_MALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_ADDMARKERS_REALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_REPLACE_1_REGCOMP_FAILED_RM, // -----------------  50
  FRAGMENT_FILE_SARH_REPLACE_1_REALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_REPLACE_1_REGEXEC_FAILED_RM,
  FRAGMENT_FILE_SARH_HEADERS_REALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_HEADER_REALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_READFILE_BUFFER_MALLOC_FAILED_RM, // ------------  55
  FRAGMENT_FILE_SARH_READFILE_FOPEN_FAILED_RM,
  FRAGMENT_FILE_SARH_ADDMARKERS_IN_LOOP_REALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_REPLACE_2_REGCOMP_FAILED_RM,
  FRAGMENT_FILE_SARH_REPLACE_2_REALLOC_FAILED_RM,
  FRAGMENT_FILE_SARH_REPLACE_2_REGEXEC_FAILED_RM, // -----------------  60
  VERTEX_FILE_SARH_REGEXEC_FAILED_RM,
  VERTEX_FILE_ILS_REPLACE_REGCOMP_FAILED_RM,
  VERTEX_FILE_ILS_REPLACE_REALLOC_FAILED_RM,
  VERTEX_FILE_ILS_REPLACE_REGEXEC_FAILED_RM,
  VERTEX_FILE_ILS_REGCOMP_FAILED_RM, // ------------------------------  65
  VERTEX_FILE_ILS_REGEXEC_FAILED_RM,
  FRAGMENT_FILE_SARH_REGEXEC_FAILED_RM,
  FRAGMENT_FILE_ILS_REPLACE_REGCOMP_FAILED_RM,
  FRAGMENT_FILE_ILS_REPLACE_REALLOC_FAILED_RM,
  FRAGMENT_FILE_ILS_REPLACE_REGEXEC_FAILED_RM, // --------------------  70
  FRAGMENT_FILE_ILS_REGCOMP_FAILED_RM,
  FRAGMENT_FILE_ILS_REGEXEC_FAILED_RM,
#if DEBUG
  XCREATEDEBUGWINDOW_FAILED_RM,
#endif
  RM_NB
};

typedef struct
{
  enum RoadmapID id;
  char* glsl_file;
} Roadmap;

#define VERB(v, stmt) if (v) { \
  stmt; \
}

typedef struct
{
  Display* display;
  GLXContext glx_context;
  Window window;
#if DEBUG
  Window debug_window;
  XEvent event;
#endif
  XWindowAttributes window_attribs;
  XVisualInfo* visual_info;
  Colormap cmap;
} Context;

typedef struct
{
  char* fshaderpath;
  char* vshaderpath;
  char* vertex_file;
  char* fragment_file;
  GLuint vertex_shader;
  GLuint fragment_shader;
  GLuint program;
} Shaders;

typedef struct
{
  png_structp parser;
  png_infop info;
  png_bytep* row_pointers;
  uint8_t* data;
  FILE* file;
  char* path;
  GLuint texture;
} PNG;

typedef struct
{
  GLuint array;
  GLuint buffer;
} Vertices;

typedef struct
{
  Context* context;
  Shaders* shaders;
  PNG* png;
  Vertices* vertices;
  bool* verbose;
  Roadmap* roadmap;
} Aggregate;

void freeContext(Context* context, bool verbose);
void freeProgram(Shaders* shaders, bool verbose, Roadmap* roadmap);
void freePng(PNG* png, bool verbose);
void freePaths(Shaders* shaders, PNG* png, bool verbose);
void freeVertices(Vertices* vertices, bool verbose);

void aggregateContext(Context* context);
void aggregateShaders(Shaders* shaders);
void aggregatePng(PNG* png);
void aggregateVertices(Vertices* vertices);
void aggregateVerbose(bool* verbose);
void aggregateRoadmap(Roadmap* roadmap);

void exitHandler();
void checkOpenGLError(const char* stmt, const char* fname, int line);

double timediff(struct timeval* start, struct timeval* end);

#define GL_CHECK(stmt) do { \
  stmt; \
  checkOpenGLError(#stmt, __FILE__, __LINE__); \
} while (0)

#define MISSINGMAIN_VERTEX_SHADER 65
#define ERRONEOUS_VERTEX_SHADER 80
#define ERRONEOUS_FRAGMENT_SHADER 156

#endif
