#!/usr/bin/env bash

[[ ${#} -ne 1 ]] || [[ ${1} -ne 1 && ${1} -ne 2 ]] \
  && echo "You have to give 1 argument to this script: 1 or 2\n" && exit 1

if [[ ${1} -eq 1 ]]; then
  declare -r FILE="src/x11_init.c"

  [[ ! -d glfw ]] && git clone https://github.com/glfw/glfw.git

  [[ ! -f glfw/${FILE} ]] && echo "glfw/${FILE} does not exist\n" && exit 1

  cd glfw && git fetch --all \
    && git checkout tags/$(git describe --tags \
      $(git rev-list --tags --max-count=1))

  [[ $? -eq 0 ]] && CAT="" && while IFS= read -r LINE; do
    CAT="${CAT}${LINE}\n";
  done < ${FILE} && CAT="${CAT::-2}"

  [[ $? -eq 0 ]] && echo -e \
    "${CAT/\"_NET_WM_WINDOW_TYPE_NORMAL\"/\"_NET_WM_WINDOW_TYPE_DESKTOP\"}" \
      > ${FILE}
elif [[ ${1} -eq 2 ]]; then
  declare -r PWD_BAK=${PWD}

  cd glfw && cmake -DCMAKE_INSTALL_PREFIX=${PWD_BAK} -S . -B build \
    && cd build && make clean && make && make install
fi
