name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v2.0.5
    - name: Check zig is canonical
      shell: bash
      run: |
        zig fmt --check .
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        profile:
          - 'zig build'
          - 'zig build -Ddev'
          - 'zig build -Dturbo'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v2.0.5

    - name: Build
      run: ${{ matrix.profile }}
