name: new-tag

on:
  workflow_dispatch:
    inputs:
      new-tag:
        description: 'New tag'
        required: true

jobs:
  new-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository }}"

    - name: Setup git user information, create and push new tag
      env:
        NAME: "GitHub Actions[bot]"
        EMAIL: "<>"
        NEW_TAG: "${{ github.event.inputs.new-tag }}"
        GH_TOKEN: "${{ github.token }}"
      shell: bash
      run: |
        git config user.name "${NAME}"
        git config user.email "${EMAIL}"
        git tag "${NEW_TAG}"
        git push --tags
