name: cd pong

on:
  repository_dispatch:
    types:
      - ping-from-cimgui.zig
      - ping-from-shaderc.zig

jobs:
  pong:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository }}"
        token: "${{ secrets.PAT }}"

    - name: Setup git user information
      env:
        BRANCH: "bot"
        EMAIL: "<>"
        NAME: "GitHub Actions[bot]"
      shell: bash
      run: |
        git config user.name "${NAME}"
        git config user.email "${EMAIL}"
        git checkout -b "${BRANCH}"

    - name: Setup Zig
      uses: mlugg/setup-zig@v2.0.5
    - name: Update the build.zig.zon
      env:
        URL: "git+${{ github.server_url }}/${{ github.repository_owner }}/${{ github.event.client_payload.from }}#${{ github.event.client_payload.tag }}"
      shell: bash
      run: |
        zig fetch --save "${URL}"

    - name: Diff
      id: diff
      shell: bash
      run: |
        diffs="$(git diff HEAD --name-only | wc -l)"
        printf 'len=%s\n' "${diffs}" >> "${GITHUB_OUTPUT}"

    - name: Create Pull Request
      if: steps.diff.outputs.len != '0'
      env:
        BRANCH: "bot"
        DEFAULT: "trunk"
        GH_TOKEN: "${{ secrets.PAT }}"
        TITLE: "Update dependencies"
      shell: bash
      run: |
        git add -A
        git commit -m "CD: ${TITLE}"
        git push --force --set-upstream origin "${BRANCH}"
        gh pr create --base "${DEFAULT}" --fill --assignee "${GITHUB_REPOSITORY_OWNER}" || :
